# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Jan  2 12:22:27 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(752, 607)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(711, 497))
        MainWindow.setMaximumSize(QtCore.QSize(752, 607))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/film.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/film.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_inp = QtGui.QFrame(self.centralwidget)
        self.frame_inp.setGeometry(QtCore.QRect(0, 1, 431, 61))
        self.frame_inp.setStyleSheet(_fromUtf8("QFrame#frame_inp{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.00819672 rgba(29, 59, 77, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}"))
        self.frame_inp.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_inp.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_inp.setObjectName(_fromUtf8("frame_inp"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_inp)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lne_url = QtGui.QLineEdit(self.frame_inp)
        self.lne_url.setObjectName(_fromUtf8("lne_url"))
        self.horizontalLayout.addWidget(self.lne_url)
        self.lbl_dontchange = QtGui.QLabel(self.frame_inp)
        self.lbl_dontchange.setObjectName(_fromUtf8("lbl_dontchange"))
        self.horizontalLayout.addWidget(self.lbl_dontchange)
        self.cmb_plot = QtGui.QComboBox(self.frame_inp)
        self.cmb_plot.setObjectName(_fromUtf8("cmb_plot"))
        self.cmb_plot.addItem(_fromUtf8(""))
        self.cmb_plot.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmb_plot)
        self.btn_search = QtGui.QToolButton(self.frame_inp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/film.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon1)
        self.btn_search.setIconSize(QtCore.QSize(32, 32))
        self.btn_search.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.horizontalLayout.addWidget(self.btn_search)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.lbl_plot = QtGui.QLabel(self.centralwidget)
        self.lbl_plot.setGeometry(QtCore.QRect(0, 430, 751, 131))
        self.lbl_plot.setText(_fromUtf8(""))
        self.lbl_plot.setObjectName(_fromUtf8("lbl_plot"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 61, 431, 271))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.txtb_data = QtGui.QTextBrowser(self.layoutWidget)
        self.txtb_data.setObjectName(_fromUtf8("txtb_data"))
        self.verticalLayout.addWidget(self.txtb_data)
        self.lbl_pic = QtGui.QLabel(self.centralwidget)
        self.lbl_pic.setGeometry(QtCore.QRect(440, -4, 301, 431))
        self.lbl_pic.setObjectName(_fromUtf8("lbl_pic"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/drop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setIconVisibleInMenu(True)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionPaste = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/combo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon3)
        self.actionPaste.setIconVisibleInMenu(True)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionPaste_from_clipboard = QtGui.QAction(MainWindow)
        self.actionPaste_from_clipboard.setIcon(icon3)
        self.actionPaste_from_clipboard.setIconVisibleInMenu(True)
        self.actionPaste_from_clipboard.setObjectName(_fromUtf8("actionPaste_from_clipboard"))
        self.actionUsage = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/page.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsage.setIcon(icon4)
        self.actionUsage.setIconVisibleInMenu(True)
        self.actionUsage.setObjectName(_fromUtf8("actionUsage"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionPaste_from_clipboard)
        self.menuHelp.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionPaste, QtCore.SIGNAL(_fromUtf8("activated()")), self.lne_url.paste)
        QtCore.QObject.connect(self.actionPaste_from_clipboard, QtCore.SIGNAL(_fromUtf8("activated()")), self.lne_url.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "movie ratings viewer", None))
        self.lne_url.setText(_translate("MainWindow", "enter the movie name", None))
        self.lbl_dontchange.setText(_translate("MainWindow", "    plot ", None))
        self.cmb_plot.setItemText(0, _translate("MainWindow", "short", None))
        self.cmb_plot.setItemText(1, _translate("MainWindow", "long", None))
        self.btn_search.setText(_translate("MainWindow", "search", None))
        self.btn_search.setShortcut(_translate("MainWindow", "Return", None))
        self.lbl_pic.setText(_translate("MainWindow", "TextLabel", None))
        self.menuFile.setTitle(_translate("MainWindow", "file", None))
        self.menuEdit.setTitle(_translate("MainWindow", "edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "help", None))
        self.statusbar.setStatusTip(_translate("MainWindow", "movie ratings viewer", None))
        self.actionClose.setText(_translate("MainWindow", "close", None))
        self.actionClose.setStatusTip(_translate("MainWindow", "closes the window", None))
        self.actionPaste.setText(_translate("MainWindow", "paste", None))
        self.actionPaste.setStatusTip(_translate("MainWindow", "paste the movie title or imdb reference", None))
        self.actionPaste_from_clipboard.setText(_translate("MainWindow", "paste from clipboard", None))
        self.actionPaste_from_clipboard.setStatusTip(_translate("MainWindow", "paste the contents from clipboard", None))
        self.actionUsage.setText(_translate("MainWindow", "usage", None))
        self.actionUsage.setStatusTip(_translate("MainWindow", "click for to see how to use this program", None))
        self.actionAbout.setText(_translate("MainWindow", "about", None))
        self.actionAbout.setStatusTip(_translate("MainWindow", "about the author and the license", None))

import resource
